<?php
/**
 * @file
 * Install and Uninstall processes for disclaimer.
 */

/**
 * Create tables on install
 */
function disclaimer_install() {
  drupal_set_message(t('To configure your disclaimer. Go to the <a href="!url">disclaimer setting page</a>.', array('!url' => url('admin/settings/disclaimer'))));
}

/**
 * Implementation of hook_uninstall().
 */
function disclaimer_uninstall() {
  // Delete all global variables
  db_query("DELETE FROM {variable} WHERE name LIKE 'disclaimer_%%'");
}